import { z } from "zod";
import { AnnotationTaskTypeSchema, ReviewerConfidenceSchema } from "./annotation-label";
import { DecisionAmendmentSchema } from "./reviewer-decision";

export const SamplingStrataSchema = z.object({
  sourceCategory: z.string().min(1),
  evidenceDepth: z.string().min(1),
  contentType: z.string().min(1),
  sector: z.string().min(1),
  subindustry: z.string().min(1),
  macroTopic: z.string().min(1),
  eventType: z.string().min(1),
  entityType: z.string().min(1),
  tickerAmbiguity: z.string().min(1),
  duplicateClass: z.string().min(1),
  syndicationClass: z.string().min(1),
  articleVersionClass: z.string().min(1),
  claimType: z.string().min(1),
  discourseClass: z.string().min(1),
  reviewRoutingStatus: z.string().min(1),
  difficulty: z.enum(["routine", "challenging", "adversarial"]),
  languageStatus: z.string().min(1),
  timeSensitivity: z.string().min(1),
  sourceRole: z.enum(["primary", "secondary", "mixed"]),
});

export const AnnotationItemSchema = z.object({
  itemId: z.string().regex(/^gold-item-\d{4}$/),
  corpusVersion: z.string().regex(/^gold-corpus-v\d+$/),
  sourceFixtureIds: z.array(z.string().min(1)).min(1),
  rawRecordIds: z.array(z.string().min(1)),
  normalizedRecordIds: z.array(z.string().min(1)),
  task: AnnotationTaskTypeSchema,
  samplingStrata: SamplingStrataSchema,
  difficultyClass: z.enum(["routine", "challenging", "adversarial"]),
  evidenceDepth: z.string().min(1),
  sourceCategory: z.string().min(1),
  eventType: z.string().min(1),
  sectorId: z.string().min(1),
  subindustryId: z.string().min(1),
  entityAmbiguityClass: z.string().min(1),
  duplicateOrSyndicationClass: z.string().min(1),
  groupId: z.string().min(1),
  evidencePackage: z.object({
    headline: z.string().min(1),
    abstract: z.string().nullable(),
    structuredFields: z.record(z.string(), z.string()),
    permittedExcerpt: z.string().nullable(),
  }),
  allowedReviewerVisibleFields: z.array(z.string().min(1)).min(1),
  hiddenPrediction: z.record(z.string(), z.unknown()).nullable(),
  expectedReviewCount: z.number().int().min(2).max(3),
  reviewAssignmentIds: z.array(z.string().min(1)),
  reviewerDecisionIds: z.array(z.string().min(1)),
  adjudicationDecisionId: z.string().min(1).nullable(),
  finalGoldLabelId: z.string().min(1).nullable(),
  goldLabelConfidence: ReviewerConfidenceSchema.nullable(),
  reviewerNotes: z.array(z.string()),
  adjudicatorNotes: z.array(z.string()),
  provenance: z.array(z.string().min(1)).min(1),
  copyrightClassification: z.enum([
    "project_synthetic",
    "public_primary_source_fixture",
    "metadata_only",
    "permitted_short_excerpt",
  ]),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  amendmentHistory: z.array(DecisionAmendmentSchema),
  regressionFixtureStatus: z.enum(["not_reviewed", "candidate", "promoted", "ineligible"]),
  exclusionStatus: z.enum(["included", "excluded"]),
  exclusionReason: z.string().nullable(),
  finalStatus: z.enum([
    "pending_review",
    "under_review",
    "adjudication_required",
    "gold",
    "excluded",
  ]),
});

export type AnnotationItem = z.infer<typeof AnnotationItemSchema>;
