import { SourceRegistryEntrySchema, type SourceRegistryEntry } from "@cluster-mkt/core";

export const demoSourceRegistry: SourceRegistryEntry[] = [
  {
    id: "fixture-government-register",
    publisherName: "Generic Government Register",
    sourceCategory: "government_primary",
    classification: "primary",
    typicalSpecialties: ["rules", "public notices"],
    feedCapability: "unknown",
    apiCapability: "unknown",
    publicMetadataAvailable: true,
    abstractAvailable: true,
    fullTextAvailability: "public",
    podcastCapability: "none",
    transcriptCapability: "none",
    accessType: "public",
    paywallLikelihood: "none",
    termsReviewStatus: "public_primary_source",
    updateFrequency: "As published",
    knownTaggingProblems: [],
    editorialTier: "primary",
    permittedForFixtureEvidence: true,
    notes: "Invented registry entry used only to exercise primary-source rules.",
  },
  {
    id: "fixture-chip-trade-journal",
    publisherName: "Fixture Chip Trade Journal",
    sourceCategory: "trade_publication",
    classification: "secondary",
    typicalSpecialties: ["semiconductors", "supply chain"],
    feedCapability: "unknown",
    apiCapability: "unknown",
    publicMetadataAvailable: true,
    abstractAvailable: true,
    fullTextAvailability: "unknown",
    podcastCapability: "available",
    transcriptCapability: "unknown",
    accessType: "unknown",
    paywallLikelihood: "unknown",
    termsReviewStatus: "not_reviewed",
    updateFrequency: "Unknown",
    knownTaggingProblems: ["May use company tickers as ordinary words."],
    editorialTier: "specialist",
    permittedForFixtureEvidence: true,
    notes: "Invented publisher. Capability fields do not imply legal authorization.",
  },
  {
    id: "fixture-company-newsroom",
    publisherName: "Fixture Company Newsroom",
    sourceCategory: "company_primary",
    classification: "primary",
    typicalSpecialties: ["company announcements"],
    feedCapability: "unknown",
    apiCapability: "none",
    publicMetadataAvailable: true,
    abstractAvailable: true,
    fullTextAvailability: "public",
    podcastCapability: "none",
    transcriptCapability: "none",
    accessType: "public",
    paywallLikelihood: "none",
    termsReviewStatus: "requires_manual_review",
    updateFrequency: "As published",
    knownTaggingProblems: ["Company claims require independent corroboration."],
    editorialTier: "primary",
    permittedForFixtureEvidence: true,
    notes: "Fixture entry; a public webpage alone is not treated as authorization.",
  },
].map((entry) => SourceRegistryEntrySchema.parse(entry));
