import {
  OperationalSourceRegistryEntrySchema,
  type OperationalSourceRegistryEntry,
} from "@cluster-mkt/core";

const base = {
  geographicScope: ["United States"],
  authenticationRequired: false,
  subscriptionLikelihood: "none" as const,
  paywallLikelihood: "none" as const,
  technicalStatus: "fixture_only" as const,
  legalReviewStatus: "fixture_reviewed" as const,
  liveEligibility: "fixture_only" as const,
  retrievalFrequencyCeilingMinutes: 60,
  retryPolicyId: "fixture-standard",
  rateLimitPolicyId: "fixture-local",
  userAgentRequirement: "offline-fixture-agent",
  attributionRequirement: "Preserve fixture source identity.",
  knownDuplicateBehavior: [] as string[],
  knownSyndicationBehavior: [] as string[],
  knownCanonicalUrlBehavior: [] as string[],
  knownUpdateBehavior: [] as string[],
  knownTaggingProblems: [] as string[],
  futureLiveRetrievalEligible: false,
  effectiveDate: "2026-07-29",
  registryVersion: "source-registry-v1",
};

const capabilities = (enabled: readonly string[]) => ({
  feed: enabled.includes("feed") ? ("verified_fixture" as const) : ("unavailable" as const),
  api: enabled.includes("api") ? ("verified_fixture" as const) : ("unavailable" as const),
  metadata: "verified_fixture" as const,
  abstract: enabled.includes("abstract") ? ("verified_fixture" as const) : ("unavailable" as const),
  fullText: enabled.includes("fullText") ? ("verified_fixture" as const) : ("unavailable" as const),
  podcast: enabled.includes("podcast") ? ("verified_fixture" as const) : ("unavailable" as const),
  transcript: enabled.includes("transcript")
    ? ("verified_fixture" as const)
    : ("unavailable" as const),
});

const method = (
  retrievalMethod:
    | "fixture_rss"
    | "fixture_api"
    | "fixture_filing"
    | "fixture_podcast_rss"
    | "fixture_transcript"
    | "fixture_file",
  adapterId: string,
  enabledForFixture = true,
) => ({
  method: retrievalMethod,
  adapterId,
  enabledForFixture,
  reviewed: true,
  endpointClass: "repository-local-fixture",
  notes: "Reads only checked-in fixture data; no endpoint exists.",
});

const entries: Array<Record<string, unknown>> = [
  {
    sourceId: "fixture-government-primary",
    publisherName: "Generic Government Primary Source",
    sourceFamilyId: "fixture-government-family",
    sourceCategory: "government_primary",
    classification: "primary",
    topicSpecialties: ["policy", "economic releases"],
    supportedContentTypes: ["government_release"],
    retrievalMethods: [method("fixture_rss", "mock-rss")],
    capabilities: capabilities(["feed", "abstract", "fullText"]),
    termsStatus: "public_primary_source_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Invented government fixture; no real agency endpoint is represented.",
  },
  {
    sourceId: "fixture-company-ir",
    publisherName: "Generic Company Investor Relations",
    sourceFamilyId: "fixture-company-family",
    sourceCategory: "company_primary",
    classification: "primary",
    topicSpecialties: ["company announcements"],
    supportedContentTypes: ["press_release"],
    retrievalMethods: [method("fixture_rss", "mock-rss")],
    capabilities: capabilities(["feed", "abstract", "fullText"]),
    termsStatus: "authorized_feed_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Invented issuer fixture.",
  },
  {
    sourceId: "fixture-regulatory-filing",
    publisherName: "Generic Regulatory Filing Source",
    sourceFamilyId: "fixture-regulatory-family",
    sourceCategory: "regulatory_primary",
    classification: "primary",
    topicSpecialties: ["filings"],
    supportedContentTypes: ["regulatory_filing"],
    retrievalMethods: [method("fixture_filing", "mock-filing")],
    capabilities: capabilities(["fullText"]),
    termsStatus: "public_primary_source_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Invented filing fixture.",
  },
  {
    sourceId: "fixture-financial-news-rss",
    publisherName: "Generic Financial News RSS",
    sourceFamilyId: "fixture-news-family",
    sourceCategory: "financial_news",
    classification: "secondary",
    topicSpecialties: ["markets", "technology"],
    supportedContentTypes: ["article"],
    retrievalMethods: [method("fixture_rss", "mock-rss")],
    capabilities: capabilities(["feed", "abstract"]),
    termsStatus: "authorized_feed_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Invented RSS fixture.",
  },
  {
    sourceId: "fixture-financial-news-api",
    publisherName: "Generic Financial News API",
    sourceFamilyId: "fixture-news-family",
    sourceCategory: "financial_news",
    classification: "secondary",
    topicSpecialties: ["markets"],
    supportedContentTypes: ["article"],
    retrievalMethods: [method("fixture_api", "mock-api")],
    capabilities: capabilities(["api", "abstract"]),
    termsStatus: "authorized_feed_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Invented API-shaped local fixture; there is no real API endpoint.",
  },
  {
    sourceId: "fixture-trade-publication",
    publisherName: "Generic Trade Publication",
    sourceFamilyId: "fixture-trade-family",
    sourceCategory: "trade_publication",
    classification: "secondary",
    topicSpecialties: ["semiconductors"],
    supportedContentTypes: ["article"],
    retrievalMethods: [method("fixture_file", "mock-api")],
    capabilities: capabilities(["abstract"]),
    termsStatus: "metadata_only_approved_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Invented metadata fixture.",
  },
  {
    sourceId: "fixture-podcast-rss",
    publisherName: "Generic Podcast RSS",
    sourceFamilyId: "fixture-podcast-family",
    sourceCategory: "podcast",
    classification: "secondary",
    topicSpecialties: ["markets"],
    supportedContentTypes: ["podcast_episode"],
    retrievalMethods: [method("fixture_podcast_rss", "mock-podcast")],
    capabilities: capabilities(["feed", "podcast"]),
    termsStatus: "metadata_only_approved_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Metadata only; factual evidence prohibited without a reviewed transcript.",
  },
  {
    sourceId: "fixture-official-transcript",
    publisherName: "Generic Official Transcript",
    sourceFamilyId: "fixture-podcast-family",
    sourceCategory: "company_primary",
    classification: "primary",
    topicSpecialties: ["official statements"],
    supportedContentTypes: ["podcast_transcript"],
    retrievalMethods: [method("fixture_transcript", "mock-transcript")],
    capabilities: capabilities(["fullText", "transcript"]),
    termsStatus: "public_primary_source_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Reviewed local transcript fixture.",
  },
  {
    sourceId: "fixture-paywalled-metadata",
    publisherName: "Generic Metadata-only Paywalled Source",
    sourceFamilyId: "fixture-news-family",
    sourceCategory: "financial_news",
    classification: "secondary",
    topicSpecialties: ["markets"],
    supportedContentTypes: ["article"],
    retrievalMethods: [method("fixture_file", "mock-api")],
    capabilities: capabilities([]),
    subscriptionLikelihood: "high",
    paywallLikelihood: "high",
    termsStatus: "metadata_only_approved_fixture",
    fixtureRetrievalEnabled: true,
    notes: "Only fixture metadata is eligible; no full-text claim is made.",
  },
  {
    sourceId: "fixture-prohibited-scraper",
    publisherName: "Generic Prohibited Scraper",
    sourceFamilyId: "fixture-restricted-family",
    sourceCategory: "general_news",
    classification: "secondary",
    topicSpecialties: [],
    supportedContentTypes: ["article"],
    retrievalMethods: [
      {
        method: "prohibited_scrape",
        adapterId: "none",
        enabledForFixture: false,
        reviewed: false,
        endpointClass: "prohibited",
        notes: "Explicit negative-control fixture.",
      },
    ],
    capabilities: capabilities([]),
    termsStatus: "prohibited",
    technicalStatus: "blocked",
    legalReviewStatus: "restricted",
    fixtureRetrievalEnabled: false,
    notes: "Negative control: never selected or retrieved.",
  },
];

export const operationalSourceRegistry: OperationalSourceRegistryEntry[] = entries.map((entry) =>
  OperationalSourceRegistryEntrySchema.parse({ ...base, ...entry }),
);

export const sourceRegistryVersion = "source-registry-v1";
