import type { AgentReviewerRole } from "@cluster-mkt/core";

const allTasks: AgentReviewerRole["applicableTasks"] = [
  "source_normalization",
  "entity_resolution",
  "event_boundaries",
  "story_cluster_membership",
  "claims",
  "agreement_disagreement",
  "review_routing",
  "sector_coverage",
];

const sharedForbiddenEvidence = [
  "pipeline prediction or confidence",
  "existing gold label",
  "other reviewers' decisions",
  "adjudication outcome",
  "consensus statistics",
  "coordinator preference",
  "prior answer for this item",
  "unblinded item identifier or repository file path",
];

export const agentReviewerRoles: Record<string, AgentReviewerRole> = {
  literal_evidence_reviewer: {
    roleId: "literal_evidence_reviewer",
    purpose: "Choose the narrowest label directly supported by visible evidence.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "allowed label definitions",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Identify the narrowest label the visible text directly supports.",
      "Reject any label that requires an inference beyond the visible evidence.",
      "Flag cannot-determine when the evidence package does not resolve the question.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["supportingFields", "conflictingFields", "missingEvidence"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: [
      "Escalate when the narrowest supported label is still ambiguous between two options.",
    ],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
  source_provenance_reviewer: {
    roleId: "source_provenance_reviewer",
    purpose:
      "Evaluate source depth, source independence, syndication, primary-source status, and provenance completeness.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "allowed provenance fields",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Determine whether the source role is primary, secondary, or mixed.",
      "Determine whether apparent independent corroboration is actually syndicated.",
      "Flag incomplete or missing provenance.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["supportingFields", "missingEvidence", "explanationCodes"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: [
      "Escalate any syndication or independence determination made with low confidence.",
    ],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
  adversarial_reviewer: {
    roleId: "adversarial_reviewer",
    purpose:
      "Search for unsupported inferences, false merges, ticker collisions, hidden ambiguity, contradictory evidence, and unsafe automatic acceptance.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "allowed label definitions",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Actively look for a reason the obvious label could be wrong.",
      "Check for ordinary-language ticker collisions and false entity merges.",
      "Recommend against automatic acceptance whenever a plausible failure mode exists.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["conflictingFields", "missingEvidence", "explanationCodes"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: [
      "Escalate any identified false-acceptance risk regardless of panel majority.",
    ],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
  domain_context_reviewer: {
    roleId: "domain_context_reviewer",
    purpose:
      "Evaluate finance, policy, filing, sector, event, and quantitative context without expanding beyond evidence.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "sector and event context fields",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Situate the evidence within known finance, policy, filing, sector, or event context.",
      "Do not add facts not present in the evidence package.",
      "Flag when domain context is required but absent from the packet.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["supportingFields", "missingEvidence"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: ["Escalate when domain context materially changes the obvious label."],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
  conservative_gatekeeper: {
    roleId: "conservative_gatekeeper",
    purpose: "Decide whether the item is safe for automatic acceptance or should route to review.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "other role checklists' visible criteria",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Default to review-required whenever any material doubt exists.",
      "Never recommend automatic acceptance for a critical factual or provenance question.",
      "State the single strongest reason to withhold automatic acceptance, if any.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["explanationCodes", "missingEvidence"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: ["Escalate whenever automatic acceptance is withheld."],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
  quantitative_integrity_reviewer: {
    roleId: "quantitative_integrity_reviewer",
    purpose:
      "Review values, units, periods, denominators, revisions, rounding, and incompatible quantities.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "numeric and unit fields",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Verify units, periods, and denominators are compatible before treating figures as comparable.",
      "Check for rounding or revision issues that change the substantive claim.",
      "Flag incompatible or mismatched quantities rather than reconciling them silently.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["supportingFields", "conflictingFields"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: ["Escalate any unresolved unit, period, or denominator mismatch."],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
  event_boundary_reviewer: {
    roleId: "event_boundary_reviewer",
    purpose:
      "Review whether records concern the same event, an update, a correction, a related event, or a distinct event.",
    applicableTasks: allTasks,
    allowedEvidence: [
      "headline",
      "abstract",
      "structured evidence fields",
      "permitted excerpt",
      "event and timing fields",
    ],
    forbiddenEvidence: sharedForbiddenEvidence,
    requiredChecklist: [
      "Determine event identity from structured signature fields, not entity plus date alone.",
      "Distinguish update, correction, proposal, final action, rumor, and confirmation.",
      "Flag ambiguous event boundaries rather than merging by default.",
    ],
    allowedLabelPolicy: "task_label_set",
    requiredExplanationFields: ["supportingFields", "conflictingFields", "explanationCodes"],
    confidenceScale: ["low", "medium", "high"],
    escalationRules: ["Escalate any event-merge decision made with less than high confidence."],
    promptVersion: "agent-role-prompt-v1",
    roleVersion: "agent-role-v1",
  },
};
