const sharedFields = {
  insufficientEvidenceOption: "insufficient_evidence",
  cannotDetermineOption: "cannot_determine",
  confidenceRequired: true,
  notesRequiredWhen: ["cannot_determine", "insufficient_evidence", "review_required"],
  escalationRule:
    "Escalate low-confidence, critical-evidence, provenance, and unresolved identity or event cases.",
} as const;

export const annotationTaskContracts = {
  source_normalization: {
    objectiveClass: "mixed",
    labels: [
      "canonical_url_relationship",
      "exact_duplicate",
      "format_variant",
      "syndicated_copy",
      "independent_report",
      "article_update",
      "new_underlying_work",
      "quarantine_eligible",
    ],
    positiveExample:
      "Two configured tracking variants with the same source article ID are one work.",
    negativeExample:
      "Two independent publishers covering one event are not syndicated merely because headlines resemble each other.",
    edgeCases: [
      "conflicting canonical claims",
      "material abstract correction",
      "unknown significant query parameter",
    ],
    ...sharedFields,
  },
  entity_resolution: {
    objectiveClass: "mixed",
    labels: [
      "candidate_entity",
      "accepted_entity",
      "rejected_false_match",
      "direct_mention",
      "inferred_mention",
      "ticker_mention",
      "sector_match",
      "macro_topic_match",
      "review_required",
    ],
    positiveExample:
      "NVDA beside earnings and shares identifies Nvidia in the bounded fixture registry.",
    negativeExample: "The phrase ‘now expects’ does not identify ServiceNow.",
    edgeCases: ["ambiguous ticker", "shared product alias", "entity only in URL slug"],
    ...sharedFields,
  },
  event_boundaries: {
    objectiveClass: "judgment_based",
    labels: [
      "same_event",
      "related_event",
      "separate_event",
      "update",
      "correction",
      "proposal",
      "final_action",
      "rumor",
      "confirmation",
      "multi_event_record",
    ],
    positiveExample:
      "A corrected figure on the same filing and reporting period is an update chain.",
    negativeExample:
      "Earnings and an analyst downgrade on the same company and date are separate events.",
    edgeCases: [
      "proposal versus final rule",
      "rumor versus confirmation",
      "one article with two events",
    ],
    ...sharedFields,
  },
  story_cluster_membership: {
    objectiveClass: "judgment_based",
    labels: ["accepted_member", "related_context", "rejected", "review_required", "quarantined"],
    positiveExample:
      "A market-reaction report explicitly tied to the announced earnings may be a distinct evidence role in the same cluster.",
    negativeExample: "Entity overlap alone does not create membership.",
    edgeCases: ["background analysis", "metadata-only record", "mixed-event record"],
    ...sharedFields,
  },
  claims: {
    objectiveClass: "mixed",
    labels: [
      "claim_present",
      "claim_absent",
      "fact",
      "interpretation",
      "quantitative",
      "attributed_statement",
      "supported",
      "partially_supported",
      "unsupported",
      "metadata_only",
    ],
    positiveExample:
      "An official filing fixture can support the exact disclosed quantity and period.",
    negativeExample: "A paywalled headline cannot support a detailed causal claim.",
    edgeCases: ["rounding tolerance", "missing denominator", "forecast versus actual"],
    ...sharedFields,
  },
  agreement_disagreement: {
    objectiveClass: "judgment_based",
    labels: [
      "equivalent",
      "compatible",
      "contradictory",
      "temporal_difference",
      "scope_difference",
      "quantitative_disagreement",
      "interpretive_disagreement",
      "apparent_disagreement",
      "superseded_claim",
    ],
    positiveExample: "Two independent works with the same proposition may form an agreement group.",
    negativeExample: "Different periods or revenue versus margin are not automatic contradictions.",
    edgeCases: ["source correction", "actual versus forecast", "different geography"],
    ...sharedFields,
  },
  review_routing: {
    objectiveClass: "mixed",
    labels: [
      "accepted",
      "review_required",
      "rejected",
      "quarantined",
      "display_eligible",
      "sector_brief_eligible",
      "blocking_reason",
    ],
    positiveExample:
      "Complete supported provenance with resolved identity may be display eligible.",
    negativeExample: "A detailed claim supported only by podcast metadata is blocked.",
    edgeCases: ["rumor-only cluster", "quarantined support", "ambiguous event boundary"],
    ...sharedFields,
  },
  sector_coverage: {
    objectiveClass: "judgment_based",
    labels: [
      "sector_wide",
      "company_led_sector_impact",
      "macro_to_sector",
      "company_specific",
      "sector_feed_include",
      "sector_feed_exclude",
      "materiality",
      "subindustry_impact",
      "anti_concentration_relevance",
    ],
    positiveExample: "A regulation affecting several subindustries can be sector-wide.",
    negativeExample:
      "A large constituent’s isolated event is not sector-wide without propagation evidence.",
    edgeCases: [
      "selective macro transmission",
      "one issuer dominates available evidence",
      "subindustry-only disruption",
    ],
    ...sharedFields,
  },
} as const;

/**
 * The reviewer-facing label registry is deliberately separate from pipeline output. Definitions
 * describe what a human can establish from the permitted evidence package; they are not expected
 * system answers. Objective labels have directly observable criteria, judgment-based labels need
 * bounded interpretation, and mixed labels combine both.
 */
export const annotationLabelDefinitions = {
  source_normalization: [
    [
      "label-canonical-url-relationship",
      "canonical_url_relationship",
      "URLs resolve by fixture evidence to the same canonical resource.",
      "objective",
      true,
    ],
    [
      "label-exact-duplicate",
      "exact_duplicate",
      "Records reproduce the same underlying work without a material content change.",
      "objective",
      true,
    ],
    [
      "label-format-variant",
      "format_variant",
      "HTML, print, mobile, or equivalent forms represent the same work.",
      "objective",
      false,
    ],
    [
      "label-syndicated-copy",
      "syndicated_copy",
      "One source republishes or attributes another source's underlying work.",
      "mixed",
      true,
    ],
    [
      "label-independent-report",
      "independent_report",
      "The record reflects independently produced reporting or primary evidence.",
      "judgment_based",
      true,
    ],
    [
      "label-article-update",
      "article_update",
      "The publisher materially updates the same underlying work.",
      "mixed",
      true,
    ],
    [
      "label-new-underlying-work",
      "new_underlying_work",
      "The record is a distinct work even if it concerns the same event.",
      "judgment_based",
      true,
    ],
    [
      "label-quarantine-eligible",
      "quarantine_eligible",
      "Conflicts, malformed identity, or prohibited evidence make automated use unsafe.",
      "mixed",
      true,
    ],
  ],
  entity_resolution: [
    [
      "label-candidate-entity",
      "candidate_entity",
      "Visible text creates a plausible registry candidate but not acceptance.",
      "objective",
      false,
    ],
    [
      "label-accepted-entity",
      "accepted_entity",
      "Visible evidence satisfies the registry's acceptance rule for the entity.",
      "mixed",
      true,
    ],
    [
      "label-rejected-false-match",
      "rejected_false_match",
      "The apparent match is ordinary language, another referent, or otherwise false.",
      "mixed",
      true,
    ],
    [
      "label-direct-mention",
      "direct_mention",
      "The entity is explicitly named or unambiguously identified in permitted evidence.",
      "objective",
      true,
    ],
    [
      "label-inferred-mention",
      "inferred_mention",
      "The entity is implied but not explicitly identified.",
      "judgment_based",
      false,
    ],
    [
      "label-ticker-mention",
      "ticker_mention",
      "The visible token is used as a security ticker in context.",
      "mixed",
      true,
    ],
    [
      "label-sector-match",
      "sector_match",
      "The visible evidence explicitly concerns the bounded sector.",
      "mixed",
      false,
    ],
    [
      "label-macro-topic-match",
      "macro_topic_match",
      "The visible evidence explicitly concerns the configured macro topic.",
      "mixed",
      false,
    ],
    [
      "label-entity-review-required",
      "review_required",
      "Identity cannot be safely accepted or rejected without qualified review.",
      "judgment_based",
      true,
    ],
  ],
  event_boundaries: [
    [
      "label-same-event",
      "same_event",
      "Records describe the same bounded occurrence or action.",
      "judgment_based",
      true,
    ],
    [
      "label-related-event",
      "related_event",
      "Events are connected contextually but retain separate identities.",
      "judgment_based",
      true,
    ],
    [
      "label-separate-event",
      "separate_event",
      "Material action, object, period, geography, or event type differs.",
      "judgment_based",
      true,
    ],
    [
      "label-event-update",
      "update",
      "Later evidence updates the same event without replacing its identity.",
      "mixed",
      true,
    ],
    [
      "label-event-correction",
      "correction",
      "Later evidence explicitly corrects a prior statement about the event.",
      "objective",
      true,
    ],
    [
      "label-proposal",
      "proposal",
      "The action remains proposed, draft, or pending.",
      "objective",
      true,
    ],
    [
      "label-final-action",
      "final_action",
      "The action is adopted, issued, completed, or otherwise final.",
      "objective",
      true,
    ],
    [
      "label-rumor",
      "rumor",
      "The proposition is unconfirmed or attributed to speculation.",
      "mixed",
      true,
    ],
    [
      "label-confirmation",
      "confirmation",
      "Qualified visible evidence confirms the previously uncertain event.",
      "mixed",
      true,
    ],
    [
      "label-multi-event-record",
      "multi_event_record",
      "One record materially describes more than one separable event.",
      "judgment_based",
      true,
    ],
  ],
  story_cluster_membership: [
    [
      "label-accepted-member",
      "accepted_member",
      "The record belongs to the cluster's event boundary and has an eligible evidence role.",
      "judgment_based",
      true,
    ],
    [
      "label-related-context",
      "related_context",
      "The record is useful context but is not direct event evidence.",
      "judgment_based",
      false,
    ],
    [
      "label-cluster-rejected",
      "rejected",
      "The record is outside the bounded cluster.",
      "judgment_based",
      true,
    ],
    [
      "label-cluster-review-required",
      "review_required",
      "Membership cannot be resolved safely from the visible evidence.",
      "judgment_based",
      true,
    ],
    [
      "label-cluster-quarantined",
      "quarantined",
      "The record is barred from accepted output pending a separate release decision.",
      "objective",
      true,
    ],
  ],
  claims: [
    [
      "label-claim-present",
      "claim_present",
      "The proposed proposition appears in the permitted evidence.",
      "objective",
      true,
    ],
    [
      "label-claim-absent",
      "claim_absent",
      "The proposed proposition does not appear in the permitted evidence.",
      "objective",
      true,
    ],
    [
      "label-claim-fact",
      "fact",
      "The proposition is presented as a verifiable occurrence, state, or quantity.",
      "mixed",
      true,
    ],
    [
      "label-claim-interpretation",
      "interpretation",
      "The proposition explains, evaluates, or infers meaning beyond direct facts.",
      "judgment_based",
      false,
    ],
    [
      "label-claim-quantitative",
      "quantitative",
      "The proposition contains a material number, unit, period, or comparison.",
      "objective",
      true,
    ],
    [
      "label-attributed-statement",
      "attributed_statement",
      "The proposition is explicitly attributed to a person or organization.",
      "objective",
      true,
    ],
    [
      "label-claim-supported",
      "supported",
      "Permitted evidence supports the complete bounded proposition.",
      "mixed",
      true,
    ],
    [
      "label-claim-partially-supported",
      "partially_supported",
      "Permitted evidence supports only part of the proposition.",
      "mixed",
      true,
    ],
    [
      "label-claim-unsupported",
      "unsupported",
      "Permitted evidence does not support the proposition.",
      "mixed",
      true,
    ],
    [
      "label-claim-metadata-only",
      "metadata_only",
      "Only source or episode metadata is visible; factual support is unavailable.",
      "objective",
      true,
    ],
  ],
  agreement_disagreement: [
    [
      "label-equivalent",
      "equivalent",
      "Claims express the same bounded proposition.",
      "judgment_based",
      true,
    ],
    [
      "label-compatible",
      "compatible",
      "Claims can both be true without expressing the same proposition.",
      "judgment_based",
      false,
    ],
    [
      "label-contradictory",
      "contradictory",
      "Claims cannot both be true under the same scope, time, unit, and attribution.",
      "judgment_based",
      true,
    ],
    [
      "label-temporal-difference",
      "temporal_difference",
      "The apparent difference is explained by distinct times or periods.",
      "mixed",
      true,
    ],
    [
      "label-scope-difference",
      "scope_difference",
      "The apparent difference is explained by geography, population, product, or other scope.",
      "mixed",
      true,
    ],
    [
      "label-quantitative-disagreement",
      "quantitative_disagreement",
      "Comparable quantities materially conflict after normalizing units and periods.",
      "mixed",
      true,
    ],
    [
      "label-interpretive-disagreement",
      "interpretive_disagreement",
      "Sources draw materially different interpretations from compatible facts.",
      "judgment_based",
      false,
    ],
    [
      "label-apparent-disagreement",
      "apparent_disagreement",
      "Wording differs, but scope-aware comparison shows no genuine conflict.",
      "judgment_based",
      true,
    ],
    [
      "label-superseded-claim",
      "superseded_claim",
      "A later correction or authoritative update replaces the earlier claim.",
      "mixed",
      true,
    ],
  ],
  review_routing: [
    [
      "label-routing-accepted",
      "accepted",
      "All task-specific acceptance and evidence gates are satisfied.",
      "mixed",
      true,
    ],
    [
      "label-routing-review-required",
      "review_required",
      "A resolvable ambiguity or high-risk judgment requires human review.",
      "judgment_based",
      true,
    ],
    [
      "label-routing-rejected",
      "rejected",
      "The record fails a substantive acceptance rule.",
      "mixed",
      true,
    ],
    [
      "label-routing-quarantined",
      "quarantined",
      "The record is isolated because a critical safety or provenance rule is implicated.",
      "objective",
      true,
    ],
    [
      "label-display-eligible",
      "display_eligible",
      "All visible-claim, provenance, review, and terminal-state gates permit display.",
      "objective",
      true,
    ],
    [
      "label-sector-brief-eligible",
      "sector_brief_eligible",
      "The accepted cluster also satisfies Sector Brief scope and evidence rules.",
      "mixed",
      true,
    ],
    [
      "label-blocking-reason",
      "blocking_reason",
      "At least one explicit rule prevents acceptance or display.",
      "objective",
      true,
    ],
  ],
  sector_coverage: [
    [
      "label-sector-wide",
      "sector_wide",
      "Evidence demonstrates material breadth across the sector rather than one issuer.",
      "judgment_based",
      true,
    ],
    [
      "label-company-led-sector-impact",
      "company_led_sector_impact",
      "A company-led event has demonstrated effects beyond that company.",
      "judgment_based",
      true,
    ],
    [
      "label-macro-to-sector",
      "macro_to_sector",
      "A macro event has a supported, material transmission path to the sector.",
      "judgment_based",
      true,
    ],
    [
      "label-company-specific",
      "company_specific",
      "Evidence remains bounded to one issuer or its direct counterparties.",
      "judgment_based",
      true,
    ],
    [
      "label-sector-feed-include",
      "sector_feed_include",
      "The item meets configured sector-feed relevance and quality gates.",
      "mixed",
      true,
    ],
    [
      "label-sector-feed-exclude",
      "sector_feed_exclude",
      "The item does not meet sector-feed relevance or quality gates.",
      "mixed",
      true,
    ],
    [
      "label-sector-materiality",
      "materiality",
      "The supported impact is consequential enough for the bounded sector context.",
      "judgment_based",
      true,
    ],
    [
      "label-subindustry-impact",
      "subindustry_impact",
      "Evidence supports material impact within a named subindustry but not necessarily the full sector.",
      "judgment_based",
      true,
    ],
    [
      "label-anti-concentration-relevance",
      "anti_concentration_relevance",
      "The item adds defensible breadth and is not present only because one issuer dominates coverage.",
      "judgment_based",
      true,
    ],
  ],
} as const;
